### ISSUE TITLE
NO CODE??????? SCAM??????????

### ISSUE THREAD

**Issue by Test123488** [minkcrypto/CPUchainAndroidMiningLibrary#1]
YO SO WHERE’S THE CODE??? SOUNDS LIKE A SCAM.

WHERE’S THE CODE @minkcrypto 

UNLESS U COPY FROM SOMEONE ELSE???????????

OOOOOOPPPPPPP

COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT

CANT MAKE ORIGINAL CODE, MUST COPY HMMMMMMMMMMM 🤔 🤔  🤔. 🤔  🤔  🤔  🤔  🤔  🤔  🤔  🤔  🤔  🤔  🤔  🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔

**Comment by Test123488** [comment]
![695DD264-82CA-4DCE-91F0-0ADA446074FA](https://user-images.githubusercontent.com/56895206/71821694-bae1a380-30cd-11ea-96ed-027d0ea0ea82.jpeg)

🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 
COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT COPYCAT
🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨

**Comment by Test123488** [comment]
Are you going to respond????????? Closing issue then. Ur copycat

**Comment by minkcrypto** [comment]
Hello @cryptozeny

**Comment by minkcrypto** [comment]
https://github.com/randombox1234 is this yours also? @Test123488 @cryptozeny

**Comment by minkcrypto** [comment]
Right now I am doing other work so I may be slow for respond, however I wouldn't be hurry for your trolling @cryptozeny @Test123488 😂
